version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my-project-nginx
    volumes:
    - ./dist:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 
    networks:
      - shared_network

networks:
  shared_network:
    external: true